### PR TITLE
feat: update packages to make it compatible with flutter 3.22.X

### PR DESCRIPTION
**Pull request by specOper99**

### CODE REVIEW

**Comment by cristipufu** [comment]
@specOper99 You also need to update the new version here: [lib/aptabase_flutter.dart](https://github.com/aptabase/aptabase_flutter/blob/main/lib/aptabase_flutter.dart#L22)
Let's also add the changelog here: https://github.com/aptabase/aptabase_flutter/blob/main/CHANGELOG.md

**Comment by specOper99** [comment]
Sorry my bad didn't notice, now you can check it out

**Comment by cristipufu** [comment]
thanks @specOper99!

btw what's your opinion on https://github.com/aptabase/aptabase_flutter/pull/8?

**Comment by specOper99** [comment]
Hello @cristipufu sorry for my late response
I checked it out today and I think he did a great work but there are some inconsistency with the formatting (mostly won't affect the performance) but the changes needs some testing on multiple users to make sure it will work efficiently
My suggestion is to create a beta release `v0.4.1b` to provide it for the users in order to test it

**Pull request merged**
