### PR TITLE
Persist events when offline and save them when online

### PR DESCRIPTION
**Pull request by flutter-painter**
Good evening @goenning,

Here is the long-awaited feature,
I tested it on my own app

### CODE REVIEW

**Comment by goenning** [comment]
Hey @flutter-painter thanks for the PR, I'll have a look later this week :)

**Comment by goenning** [comment]
Ok so I went through the PR and my concern is that this solution is very distant from what's been added to other SDKs. On the other hand, it also introduces some new things that I like.

In general, most SDKs are not batching events, so when you do `trackEvent` it adds the event to a queue and then a background interval will constantly try to push it to the server using an endpoint that accepts an array of events. It that fails, it retries after 60 seconds. 

However those other SDKs do not store events, so if the app is closed and the flush fails because the device is offline, those events are lost. That's something this PR fixes and is something I would like to add to other SDKs too.

I think this is a step in the right direction, I do have a few concerns though so let's see if there's anything we can do about it:

1. Is it possible to have the `service` being an optional parameter of the Init instead of TrackEvent? I think it makes more sense to be there.
2. It seems like one of the dependencies for connectivity check do no support web platforms. Is there a better replacement? Or maybe conditional compilation (not sure if that's something we can do in Flutter).
3. Instead of looping through events and pushing one by one, we could now use the new endpoint that accepts multiple events, that might simplify a bit the code.
4. Is sembast popular?

Let me know what your thoughts are! Great to see some unit tests too :D

**Comment by flutter-painter** [comment]
Hi Guilherm,
In short : 

1.  Passing the service (and db) at init, will create two states of the db. The app will edit the db for internal logic while aptabase will edit the db whenever an event is sparked. This might end up ugly... 
To avoid this issue, client could use a dedicated db for tracking aptabase event. I updated the example accordingly.
I agree it is lighter. Just note that the init needs to be run a second time after the materialApp once the service is available.

2. Well-spotted. I think web will build with this package (internet_connection_checker), I just separate the code snippet that is web incompatible in a file that only runs after the OS check. It should do.

3. Sure, batch sending is more efficient. But where is the endpoint ? 

4. Sembast counts 742 stars, it was the pioneer for local persistence in flutter both sql and nosql. Yet the whole purpose of using a service is that this could easily be extended for other persistence solution such as Hive, Moor, etc.

This should answer 1, 2 and 4.
I await your hint on 3, will implement and will manually test the whole lot before pushing the next commit.

**Comment by flutter-painter** [comment]
Hi Guilherm !

1. How about simply adding a method for opening persistence ? It will only be used by those who need it and avoid double init. (If we make db internal, then we need to handle other logic that I is heavy and irrelevant for aptabase, see the added depencies for sembast in the example .yaml).

2. Thank you for providing more insight on the way you send batch events in other sdks, Triggering something every x seconds must exist already indeed, will search.

I understand your question is about adding persistence for other sdks.
First do you check for connectivity (and I mean real internet check, not checking if wifi is on) ?
I think this logic is only relevant if you know that the user has a working internet connexion.

Assuming it the case ;
Why do you discard events if the API call fails with 4xx ? 
Is it because you assume the events are yielding the error ? Could the call fail because of another reason ? If this is the case I why not add the event in persistence ?
Regarding network error, you assume that network will resume during this session. Couldn't this lead to many useless calls if network remains unstable ? I guess this depends on the context, but in doubt the frugal approach seems the safest.

I would tend to add events to db whenever connectivity is off, and whenever the call fails.
And I would send persisted past events whenever a live call works.

Are you able to check if "the app closes or goes to the background" in **all other SDKs** ?
In Flutter you wouldn't easily get this info within your package. You would need the client to pass it to you, like we did here for the service.
My point here is that using persistence you do not really need this behaviour.

**Comment by goenning** [comment]
1. Yeah that sounds like a good idea.
2. OK

No, we don't do any connectivity check. I think that it's simpler (and requires less dependencies) to try sending the request. If there's no connectivity, it'll fail fast and retry later anyway.

We discard events because if the server says there's an issue with the data, retrying it later won't change the response. That's why we only do it on 4xx. It could fail for other reasons, like a server error or device being offline, which is why we retry later. Will it result in useless calls? Yes, but what's the impact of those? I don't think it's noticeable at all.

The React Native SDK and Swift SDK both uses a system event whenever the app goes to background, which gives us time to do one last try. I'm confident the platforms have this functionality, however I don't know if Flutter exposes that in a way that's easy for the SDK to hook up to.

**Comment by flutter-painter** [comment]
Hi @goenning,
Happy new year,
Please let me know how you stand on this PR

**Comment by goenning** [comment]
I'll have a look again this week @flutter-painter slowly restarting my routing after the NY holidays :)

**Comment by goenning** [comment]
I went through the PR again and I like this new method of setting up persistence. I do however still think the logic around tracking+save+send events is too complex, the `trackEvent` is doing too many things.

For example
- in some cases batch is used, while in others it's still doing calls one by one
- there's one edge case missing: if the user is offline and there is no persistence, the event is lost immediately

What you think about a simplified logic like this:
- trackEvent simply enqueues the event (in memory)
- a timer runs every X seconds and gets all events from the queue and push to the server using the batch API
- if it fails with > 500, store all events if persistence is enabled otherwise drop events.
- if response is < 500, it's because it succeeded, if persistence is enabled, tale all events from storage and send those too
- use the [SystemChannels/lifecycle](https://api.flutter.dev/flutter/services/SystemChannels/lifecycle-constant.html) to store events from memory to storage if the user moves the app to background.

In this case we keep trackEvent very simple and fast, it only enqueues in memory and there's no need for additional network libraries.

What you think? Did I miss something?

**Comment by flutter-painter** [comment]
Hi,
Indeed, this could be simplified but your suggestions would require a lot of rework on the current design.
I delivered what we agreed on and let you take it from there.

**Comment by cristipufu** [comment]
@flutter-painter thanks for your contribution, we merged the other PR

**Pull request closed without merging**
